version: "3.8"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=cubospay
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgres/data
volumes:
  data:
